Enable Py_ssize_t to avoid PY_SSIZE warnings
Addressing this annoying issue:
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Based on https://github.com/aptly-io/python-fastlz/commit/f69114f3bc148cd4a0d70eea9c173e4f093caa78,
excluded changes in .gitignore and setup.py, and use Py_ssize_t only
for Python arguments to fix 'invalid input' in decompress() in Py 3.9.

Py_ssize_t should be available since Python 2.5, wrt
https://peps.python.org/pep-0353/

Signed-off-by: PaulChanHK <19663576+PaulChanHK@users.noreply.github.com>